name: Automated test

on:
  push:
    branches: [ "master" ]

jobs:
  Linux-x86-64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build angelscript
      run: |
        cd $GITHUB_WORKSPACE/sdk/angelscript/projects/gnuc
        make
        
    
