name: Automated test
permissions:
  contents: read
  
on:
  push:
    branches: [ "master" ]

jobs:
  Linux-x86-64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
       version: latest
       platform: x64
       cc: 1
    - name: build angelscript
      run: |
        cd $GITHUB_WORKSPACE/sdk/angelscript/projects/gnuc
        make
    - name: build test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/projects/gnuc
        make
    - name: run test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/bin
        ./testgnuc > result.txt
        cat result.txt
        grep "All of the tests passed with success." result.txt
        
  Clang:      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build angelscript & test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/projects/cmake
        cmake .
        cmake --build .
    - name: run test_feature
      run: |
        cd $GITHUB_WORKSPACE/sdk/tests/test_feature/bin
        ./test_feature > result.txt
        cat result.txt
        grep "All of the tests passed with success." result.txt


        
